### ISSUE TITLE
Кнопка с выпадающим списком закладок

### ISSUE THREAD

**Issue by a7lan** [justdanpo/VivaldiPatches#2]
Спасибо за патчи, очень полезные. Но есть вопрос. Эта кнопка вызывает закладки, которые указаны в настройках для панели закладок. У меня в панели 5-6 самых нужных закладок. Остальные в других папках. Нельзя сделать, чтоб кнопка вызывала основной список закладок, а не тот что закреплен за панелью закладок?

**Comment by justdanpo** [comment]
Сделал

**Comment by a7lan** [comment]
Отлично. Спасибо!
