### ISSUE TITLE
How do you build this patches?

### ISSUE THREAD

**Issue by ManUtopiK** [justdanpo/VivaldiPatches#4]
I just want to know how did you make this patches?
Also, patches are minified, are there a non-minified version?

I play with the console and make some stuff, but I can't use React to custom stuff :/
Just for fun, this code add class to all bookmark buttons in bookmark-bar and provide ability to custom a little bit more each bookmark independently:

``` js
(function() {
    setTimeout(function () {
        var $bookmarkBar = document.getElementsByClassName('bookmark-bar');
        _.each(document.getElementsByClassName('bookmark-bar')[0].querySelectorAll('button'), function(elem) {
            //elem.className = '';

            var $img = elem.getElementsByTagName('img'),
                _class;

            // get url if it's a file or get name for folder/other
            if ($img.length) {
                _class = slugify($img[0].src.replace(/chrome:\/\/favicon\/https*:\/\/w{0,3}/, ''));
            } else {
                var $span = elem.getElementsByTagName('span');
                if ($span.length) {
                    _class = slugify($span[0].innerText);
                }
            }
            elem.classList.add(_class);
        });
    }, 3000)
})();
```

**Comment by justdanpo** [comment]
This is a bad place for such discussions. Feel free to ask questoins here: https://vivaldi.net/en-US/forum/all/8453-bundle-js-modding

I'm working on a "nextgen patches" - something like userscripts able to access/modify internal browser's components.

I'm closing the issue.
